name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build JAR
        run: mvn package -Prelease

      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/world_simulation-1.0.jar
            target/simulation.properties
            target/themes/*.json
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
